name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24']
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run Linter
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          args: --timeout=2m
      #- name: Run Tests
      # run: go test
